## TASK 1: Developing a Machine Learning Model:
A knn-classifier model has been developed using a fixed value of k = 1. The attributes have been preprocessed with MinMaxScaler() as follows:

In [135]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [136]:
df = DataFrame()
df['wingspan'] = [20, 25, 15, 18, 200, 180,10, 45, 30, 40, 12, 150,180, 150, 40]
df['lifespan'] = [5, 7, 3, 6, 20, 15,3, 15, 10, 15, 8, 25,20, 25, 8]
df['habitat'] = ['Forest', 'Forest', 'Other', 'Forest', 'Mountain', 'Mountain', 'Other', 'Other', 'Forest', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other']
df

wingspan  lifespan   habitat
0         20         5    Forest
1         25         7    Forest
2         15         3     Other
3         18         6    Forest
4        200        20  Mountain
5        180        15  Mountain
6         10         3     Other
7         45        15     Other
8         30        10    Forest
9         40        15     Other
10        12         8     Other
11       150        25     Other
12       180        20     Other
13       150        25     Other
14        40         8     Other

In [137]:
dfX = df.drop(columns = ['habitat'])
sy = df.habitat

In [138]:
from sklearn.model_selection import train_test_split
dfX_train, dfX_test, sy_train, sy_test = train_test_split(dfX, sy)

In [139]:
dfX_train, dfX_test, sy_train, sy_test;

In [140]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le

LabelEncoder()

In [141]:
le = le.fit(sy_train)
le.classes_

array(['Forest', 'Mountain', 'Other'], dtype=object)

In [142]:
y_train = le.transform(sy_train)
sy_train, y_train

(1       Forest
 10       Other
 3       Forest
 0       Forest
 4     Mountain
 8       Forest
 14       Other
 6        Other
 7        Other
 12       Other
 9        Other
 Name: habitat, dtype: object,
 array([0, 2, 0, 0, 1, 0, 2, 2, 2, 2, 2]))

In [143]:
dfX_train.to_numpy()

array([[ 25,   7],
       [ 12,   8],
       [ 18,   6],
       [ 20,   5],
       [200,  20],
       [ 30,  10],
       [ 40,   8],
       [ 10,   3],
       [ 45,  15],
       [180,  20],
       [ 40,  15]])

In [144]:
n1 = preprocessing.MinMaxScaler()
n1 = n1.fit(dfX_train.to_numpy())
X_train = n1.transform(dfX_train.to_numpy())
X_train

array([[0.07894737, 0.23529412],
       [0.01052632, 0.29411765],
       [0.04210526, 0.17647059],
       [0.05263158, 0.11764706],
       [1.        , 1.        ],
       [0.10526316, 0.41176471],
       [0.15789474, 0.29411765],
       [0.        , 0.        ],
       [0.18421053, 0.70588235],
       [0.89473684, 1.        ],
       [0.15789474, 0.70588235]])

In [145]:
X_train.shape

(11, 2)

In [146]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)
knn = knn.fit(X_train, y_train)
knn

KNeighborsClassifier(n_neighbors=1)

In [147]:
y_test = le.transform(sy_test.to_numpy())
sy_test, y_test

(11       Other
 5     Mountain
 13       Other
 2        Other
 Name: habitat, dtype: object,
 array([2, 1, 2, 2]))

In [148]:
X_test = n1.transform(dfX_test.to_numpy())
dfX_test, X_test

(    wingspan  lifespan
 11       150        25
 5        180        15
 13       150        25
 2         15         3,
 array([[0.73684211, 1.29411765],
        [0.89473684, 0.70588235],
        [0.73684211, 1.29411765],
        [0.02631579, 0.        ]]))

In [149]:
knn.predict(X_test)

array([2, 2, 2, 2])

In [150]:
y_test

array([2, 1, 2, 2])

In [151]:
knn.score(X_test, y_test)

0.75

In [152]:
knn.score(X_train, y_train)

1.0

## TASK 4: Application of the Machine Learnning Model:
The model developed has been used to predict the class of an new instance that is not part of the training or test
dataset as follows:

In [156]:
new_data = np.array([  [38, 14]  ])
X_new = n1.transform(new_data)
X_new


array([[0.14736842, 0.64705882]])

In [157]:
knn.predict(X_new)

array([2])

In [158]:
le.inverse_transform(knn.predict(X_new))

array(['Other'], dtype=object)